# -*- coding: utf-8 -*-
"""Modulo_1_Live_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N-ow1IA7X0Iyh8KuynETvPKuVVwWoYnK
"""

import polars as pl

df = pl.read_csv('ca-2022-02.csv', separator=';', try_parse_dates=True)

df.head()

df = df.with_columns(pl.col("Valor de Venda").str.replace(",", "."))

df = df.filter(pl.col("Valor de Venda") !="SN")
df = df.with_columns(pl.col("Valor de Venda").cast(pl.Float64))

df.head()

df_temp = df.select(["Regiao - Sigla", "Estado - Sigla", "Revenda", "Produto", "Data da Coleta", "Valor de Venda", "Bandeira"])

df_temp.head(50)

import matplotlib.pyplot as plt
import seaborn as sns

df_temp2 = df_temp.to_pandas()

df_temp2

len(df_temp2["Regiao - Sigla"].unique())

df_temp2["Estado - Sigla"].unique()

len(df_temp2["Estado - Sigla"].value_counts())

df_temp2["Estado - Sigla"].value_counts()

df_temp2["Regiao - Sigla"].value_counts()

182865/378077

#48% dos dados são da região Sudeste

df_temp2["Valor de Venda"].describe()

sns.boxplot(y=df_temp2["Valor de Venda"])