# -*- coding: utf-8 -*-
"""venda de carros.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gXXItR5Q5HoZeZItnytWRK1OGg-PupjY
"""

import pandas as pd
#pd.set_option("display.max_rows", 1000)
#pd.set_option("display.max_columns", 1000)

dataset=pd.read_csv("/content/db.csv", sep=";")

dataset

dataset.dtypes

dataset[["Quilometragem", "Valor"]].describe()

dataset.info()

"""# Tuplas."""

nome = "passat"
valor = 153.000
(nome, valor)

nomes_carros = tuple(["Jetta Variant", "Passat", "Crossfox", "Ds5"])
nomes_carros

type(nomes_carros)

nomes_carros = tuple(["Jetta Variant", "Passat", "Crossfox", "Ds5"])
nomes_carros

nomes_carros [0]

nomes_carros[1:3]

nomes_carros = ("Jetta Variant", "Passat", "Crossfox", "Ds5", ("Fusca", "Gol", "C4"))
nomes_carros

nomes_carros[-1]

nomes_carros[-1][1]

"""# Iterações em Tuplas

"""

nomes_carros = ("Jetta Variant", "Passat", "Crossfox", "Ds5", )
nomes_carros

for item in nomes_carros:
  print (item)

"""Desempacotamento de tuplas"""

carro_1, carro_2, carro_3, carro_4 = nomes_carros

carro_1

_, A, _, B = nomes_carros

A

B

_, C, *_ = nomes_carros

C

carros = ["jetta Variant", "passat", "crossfox", "DS5"]
carros

valores = [88078.64, 105284.98, 128495.03, 57194.65]
valores

list(zip(carros, valores))

for item in zip(carros, valores):
  print (item)

for carro, valor in zip(carros, valores):
  print(carro, valor)

for carro, valor in zip(carros, valores):
  if(valor > 100000):
    print(carro)

