# -*- coding: utf-8 -*-
"""venda de carros.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gXXItR5Q5HoZeZItnytWRK1OGg-PupjY
"""

import pandas as pd
#pd.set_option("display.max_rows", 1000)
#pd.set_option("display.max_columns", 1000)

dataset=pd.read_csv("/content/db.csv", sep=";")

dataset

dataset.dtypes

dataset[["Quilometragem", "Valor"]].describe()

dataset.info()

"""# Tuplas."""

nome = "passat"
valor = 153.000
(nome, valor)

nomes_carros = tuple(["Jetta Variant", "Passat", "Crossfox", "Ds5"])
nomes_carros

type(nomes_carros)

nomes_carros = tuple(["Jetta Variant", "Passat", "Crossfox", "Ds5"])
nomes_carros

nomes_carros [0]

nomes_carros[1:3]

nomes_carros = ("Jetta Variant", "Passat", "Crossfox", "Ds5", ("Fusca", "Gol", "C4"))
nomes_carros

nomes_carros[-1]

nomes_carros[-1][1]

"""# Iterações em Tuplas

"""

nomes_carros = ("Jetta Variant", "Passat", "Crossfox", "Ds5", )
nomes_carros

for item in nomes_carros:
  print (item)

"""Desempacotamento de tuplas"""

carro_1, carro_2, carro_3, carro_4 = nomes_carros

carro_1

_, A, _, B = nomes_carros

A

B

_, C, *_ = nomes_carros

C

carros = ["jetta Variant", "passat", "crossfox", "DS5"]
carros

valores = [88078.64, 105284.98, 128495.03, 57194.65]
valores

list(zip(carros, valores))

for item in zip(carros, valores):
  print (item)

for carro, valor in zip(carros, valores):
  print(carro, valor)

for carro, valor in zip(carros, valores):
  if(valor > 100000):
    print(carro)

nome, valor = ('Passat', 100000.0)

nomes = ['Passat', 'Crossfox']
valores = [100000.0, 75000.0]
list(zip(nomes, valores))

nomes = ['Passat', 'Crossfox', 'DS5', 'C4', 'Jetta']
kms = [15000, 12000, 32000, 8000, 50000]

for nome, km in zip(nomes, kms):
    if(km < 20000):
        print(nome)

"""## Trabalhos com Dicionários"""

carros = ["Jetta Variant", "Passat", "Crossfox"]
carros

Valores = [88078.64, 106161.94, 72832.16]
Valores

carros.index("Passat")

Valores[carros.index("Passat")]

dados = {"Jetta Variant" : 88079.64, "Passat" : 106161.94, "crossfox" : 72832.16}
dados

type(dados)

list(zip(carros,Valores))

dados = dict(zip(carros, Valores))
dados

#verificar valor de item dentro da base
dados["Passat"]

#verificar de item está na base
"Passat" in dados

#verificar de item está na base
"fusca" in dados

#verificar de item está na base
"Fusca" not in dados

#verificar numero de itens
len(dados)

#incluir novo item
dados["DS5"] = 124549.07

dados

#Eliminar item
del dados["Passat"]

dados

#retornar item
dados.update({"Passat": 106161.94})
dados

#atualizar valor e inserir novo ao mesmo tempo
dados.update({"Passat":106161.75, "Fusca":150000})
dados

"""#dict.copy"""

dadosCopy = dados.copy()
dados

#modificando apenas a base de dados "dadosCopy"
del dadosCopy["Fusca"]
dadosCopy

dados

"""#dict.pop"""

dadosCopy.pop("Passat")

dadosCopy

#inserir mensagem para se a chave não estiver
dadosCopy.pop("passat", "chave não encontrada")

"""#dict.clear"""

dadosCopy.clear()
dadosCopy

"""Iteração em dicionários
##dict.keys()
"""

dados.keys()

for key in dados.keys():
  print(dados[key])

dados.values()

"""#dict items"""

for item in dados.items():
  print(item)

for key, value in dados.items():
  print(key, value)

for key, value in dados.items():
  if (value > 100000):
    print(key)

dados2 = {
    'Crossfox': {'valor': 72000, 'ano': 2005}, 
    'DS5': {'valor': 125000, 'ano': 2015}, 
    'Fusca': {'valor': 150000, 'ano': 1976}, 
    'Jetta': {'valor': 88000, 'ano': 2010}, 
    'Passat': {'valor': 106000, 'ano': 1998}
}

for item in dados2.items():
    if(item[1]['ano'] >= 2000):
        print(item[0])

"""# Funções

Built-in Function
"""

valores = []
for valor in dados.values():
  valores.append(valor)
valores

soma = 0
for valor in dados.values():
  soma += valor
soma

list(dados.values())

sum(dados.values())

sum(dados.values(), 1000000)

help(print)

print?

