# -*- coding: utf-8 -*-
"""venda de carros.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gXXItR5Q5HoZeZItnytWRK1OGg-PupjY
"""

import pandas as pd
#pd.set_option("display.max_rows", 1000)
#pd.set_option("display.max_columns", 1000)

dataset=pd.read_csv("/content/db.csv", sep=";")

dataset

dataset.dtypes

dataset[["Quilometragem", "Valor"]].describe()

dataset.info()