# -*- coding: utf-8 -*-
"""Aquisição e visualização.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aMGfvWOKHRErkf94fkhUMOgKjjhF1iBu
"""

pip install matplotlib

pip install pandas

import pandas as pd
import matplotlib.pyplot as plt

dados=pd.read_csv('/content/A203512189_28_143_208.csv',
                  encoding='ISO-8859-1',
                  skiprows=3,
                  sep=';',
                  skipfooter=12,
                  thousands='.',
                  decimal=',')

dados.head()
dados.tail()
dados.info()
pd.options.display.float_format='{:.2f}'.format
dados.mean()

dados["2008/Ago"]

dados["2008/Ago"].mean()

import matplotlib.pyplot as plt
import matplotlib.ticker as ticker

axis = dados.plot(x="Unidade da Federação", y="2021/Dez", kind="barh", figsize=(9,6))
axis.xaxis.set_major_formatter(ticker.StrMethodFormatter("{x:,.2f}"))
plt.xticks(rotation=45)

plt.title("Valor por unidade da federação")
plt.show()

dados[["2008/Ago", "2008/Set"]].head()

dados.columns

colunas_usaveis = dados.mean().index.tolist()
colunas_usaveis.insert(0, "Unidade da Federação")
colunas_usaveis[:5]

dados_usaveis = dados[colunas_usaveis]
dados_usaveis.head()

dados_usaveis = dados_usaveis.set_index("Unidade da Federação")
dados_usaveis.head()

dados_usaveis["2019/Ago"].head()

dados_usaveis.loc["12 Acre"]

dados_usaveis.iloc[1]

dados_usaveis.plot(figsize=(14,6))

dados_usaveis.T.head()

dados_usaveis.T.plot(figsize=(12,6))

dados_usaveis.tail()

dados_usaveis=dados_usaveis.drop("Total", axis=1)
dados_usaveis.head()

dados_usaveis.T.plot(figsize=(12,6))
plt.xlabel("Mês / Ano")
plt.ylabel("Valores R$")
plt.title("Gráfico de Investimentos por Estados")
plt.legend(bbox_to_anchor=(1.0, 1.1), borderpad=1)
plt.show()

dados_usaveis.head()

dados_usaveis.T.columns

dados_usaveis.T.columns[:5]

dados_usaveis[:5]

dados_usaveis[:7].T.plot(figsize=(10,6))

dados_usaveis.sample()

dados_usaveis.sample(n=7)

dados_usaveis.sample(7).T.plot(figsize=(10,6))

import numpy as np

np.random.seed(524387)
dados_usaveis.sample(n=7)

dados_usaveis.sample(n=7).T.plot(figsize=(10,6))

dados_usaveis["Total"]=dados_usaveis.sum(axis=1)
dados_usaveis.head()

dados_usaveis.head()

ordenados_por_total = dados_usaveis.sort_values(by="Total", ascending=False)
ordenados_por_total = ordenados_por_total.drop("Total", axis=1)
ordenados_por_total.head()

ordenados_por_total.head(5).T.plot(figsize=(10,6))

ordenados_por_total=ordenados_por_total/1_000_000

axis=ordenados_por_total.head(5).T.plot(figsize=(10,6))
axis.set_ylabel("Gastos Aprovados em Milhões de Reais")
axis.set_xlabel("Mês")

meses_filtrados=ordenados_por_total.columns[47:]
ordenados_por_total[meses_filtrados].head(3).T.plot(figsize=(10,6))
axis.set_ylabel("gasto aprovado em milhões de reais")
axis.set_xlabel("mês")

def plota_gastos_por_mes(dados, figsize=(10,6)):
  axis=dados.T.plot(figsize=figsize)
  axis.set_ylabel("Gastos Aprovados em Milhões de Reais")
  axis.set_xlabel("Mês")

plota_gastos_por_mes(ordenados_por_total[meses_filtrados].head(3))

plota_gastos_por_mes(ordenados_por_total[meses_filtrados].head(3))
plt.ylim(0, 600)

plota_gastos_por_mes(ordenados_por_total[ordenados_por_total.columns[45:70]].head(3))
plt.ylim(0, 440)

plota_gastos_por_mes(ordenados_por_total[ordenados_por_total.columns[-60:]].head(3))
plt.ylim(0, 650)

plota_gastos_por_mes(ordenados_por_total[ordenados_por_total.columns[0:]].head())
plt.ylim(0, 650)

plota_gastos_por_mes(ordenados_por_total[ordenados_por_total.columns[-72:]].head())
plt.ylim(0, 650)
plt.xticks([0, 12, 24, 36, 48, 60, 72], [2015, 2016, 2017, 2018, 2019, 2020, 2021])
plt.show()

plota_gastos_por_mes(ordenados_por_total[ordenados_por_total.columns[-72:]].head())
plt.ylim(0, 650)
plt.xticks([0, 12, 24, 36, 48, 60, 72], [2015, 2016, 2017, 2018, 2019, 2020, 2021])
plt.grid(True, linestyle='--', linewidth=0.5, color="gray")
plt.show()