# -*- coding: utf-8 -*-
"""IDHM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dQ4IDROe8GK9G5TCFlraoabToGRro_B_
"""

#!pip install xlrd ou openpyxl

!pip install xlrd

"""## O que é o IDHM

Links importantes<br/>
https://www.undp.org/pt/brazil/o-que-%C3%A9-o-idhm<br/>
Base de dados Ipea<br/>
https://www.ipea.gov.br/ipeageo/arquivos/bases/IDH_2010.xls

O Índice de Desenvolvimento Humano Municipal (IDHM) é uma medida composta de indicadores de três dimensões do desenvolvimento humano: longevidade, educação e renda. O índice varia de 0 a 1. Quanto mais próximo de 1, maior o desenvolvimento humano.

O IDHM brasileiro segue as mesmas três dimensões do IDH Global - longevidade, educação e renda, mas vai além: adequa a metodologia global ao contexto brasileiro e à disponibilidade de indicadores nacionais. Embora meçam os mesmos fenômenos, os indicadores levados em conta no IDHM são mais adequados para avaliar o desenvolvimento dos municípios brasileiros. Assim, o IDHM - incluindo seus três componentes, IDHM Longevidade, IDHM Educação e IDHM Renda - conta um pouco da história dos municípios em três importantes dimensões do desenvolvimento humano durantes duas décadas da história brasileira.
"""

#Libs

import pandas as pd
import numpy as np

#libs gráficas
import plotly.express as px
import seaborn as sns
import matplotlib.pyplot as plt

#Avisos
import warnings
warnings.filterwarnings('ignore')

idhm = pd.read_excel('IDH_2010.xls')
idhm.head()

print(f'Tamanho do nosso Dataset: {idhm.shape}')

idhm.dtypes

print(f'Quantidade de dados nulos: {idhm.isnull().sum().sum()}')

#definição das novas colunas
df_idhm = idhm[['Nome da Unidade da Federação', 'Município', 'Esperança de vida ao nascer','IDHM', 'IDHM Educação', 'IDHM Longevidade', 'IDHM Renda']]

#opção para renomear, e renomeando não precisa inplace=True.
#df_idhm.rename({"Nome da Unidade da Federação":"UF", "Esperança de Vida ao Nascer":"Longevidade_idade"}, inplace=True)   OU
#df_idhm = df_idhm.rename({"Nome da Unidade da Federação":"UF", "Esperança de Vida ao Nascer":"Longevidade_idade"})

#renomear as colunas
df_idhm.columns = ['UF', 'municipio', 'longevidade_idade','idhm', 'idhm_educacao', 'idhm_longevidade', 'idhm_renda']

#df_idhm.longevidade_idade <é =>  df_idhm["longevidade_idade"] ->>>Para ver a coluna
df_idhm.longevidade_idade

df_idhm.head()

"""Informações da Base"""

df_idhm.info()

"""Valores únicos"""

df_idhm.nunique()

df_idhm.describe()

"""Primeira análise

0 - 0,499 - Baixo Desenvolvimento Humano<br/>
0,5 - 0,799 - Médio Desenvolvimento Humano<br/>
0,8 - 1 - Alto Desenvolvimento Humano
"""

def idhm_class(df):
    if df['idhm']>=0.8:
        return 'Alto Desenvolvimento Humano'
    elif df['idhm']<0.499:
        return 'Baixo Desenvolvimento Humano'
    else:
        return 'Médio Desenvolvimento Humano'

df_idhm['classe'] = df_idhm.apply(idhm_class, axis=1)
df_idhm

"""Pairplot"""

sns.pairplot(df_idhm, hue = 'classe')

"""### Análise por Estado"""

#Fitro
df_idhm_estado = pd.DataFrame(df_idhm.groupby('UF')['idhm'].mean().round(2)).reset_index()
df_idhm_estado

df_idhm_estado['classe'] = df_idhm_estado.apply(idhm_class, axis=1)
df_idhm_estado

df_idhm_estado.info()

df_idhm_estado.describe()

#Usando o MATPLOTLIB
plt.title('Gráfico Boxsplot', loc = 'left', fontsize = 18)
plt.boxplot(df_idhm_estado['idhm']);

plt.xlabel('IDHM')
plt.ylabel('Valores')

#Usando SEABORN
sns.boxplot(x=df_idhm_estado['idhm'], data=df_idhm_estado)

# Adicionar título e rótulos dos eixos
plt.title('Boxplot dos Valores por Classificação')
plt.xlabel('IDHM')
plt.ylabel('Valores')

"""Criar um gráfico de Barra"""

#Tamanho da Figura
plt.figure(figsize=(12,6))

#Paleta de Cores
Paleta_Cores = sns.color_palette('mako', len(df_idhm_estado) )
sns.set_style('darkgrid')

#Plotagem
plt.bar(df_idhm_estado['UF'], 
        df_idhm_estado['idhm'], 
        width=0.9,
        color = Paleta_Cores
        )

#Titulo
plt.title('Boxsplot sobre o IDHM', loc = 'left', fontsize = 18)

#Labels
plt.xlabel('UF', fontsize = 14)
plt.ylabel('IDH com a média dos Estados', fontsize = 14)
plt.xticks(rotation = 90);

"""Usando o Plotly"""

# Criar um gráfico de barras usando o Plotly
fig = px.bar(df_idhm_estado, x='UF', y='idhm', text='idhm', color = 'classe', color_discrete_sequence=['orange','green'])


# Adicionar título e rótulos dos eixos
fig.update_layout(title='Gráfico de Barras',
                  xaxis_title='UF',
                  yaxis_title='idhm')
fig.show()

# Usando o Plotly
fig = px.treemap(df_idhm_estado, path=['UF'], values='idhm', title='TreeMap')

# Exibir o treemap
fig.update_traces(root_color="lightgrey")



fig.show()

